#!/usr/bin/fish

set -x BSPC_DEFAULT_BORDER_WIDTH 0
set -x BSPC_HIGHLIGHT_BORDER_WIDTH 5
set -x BSPC_BORDER_COLOR 72cbcb
set -x BSPC_MARKED_BORDER_COLOR AA5775
set -x BSPC_MARKED_FOCUSED_BORDER_COLOR D82883
bspc config presel_feedback_color "#$BSPC_BORDER_COLOR"
bspc config focused_border_color "#$BSPC_BORDER_COLOR"

bspc wm --reorder-monitors HDMI1 eDP1 || true
bspc monitor -f HDMI1 || true

bspc config window_gap 0
bspc config border_width $BSPC_DEFAULT_BORDER_WIDTH

bspc config top_padding 20
bspc config automatic_scheme alternate

# Only on first load
if [ "$argv[1]" = "0" ]
    bspc rule -a Yad state=floating center=true
    bspc rule -a Lxappearance state=floating
    bspc rule -a Emacs state=tiled
    bspc rule -a 'Soffice:soffice:Full Screen' hidden=on
    bspc rule -a 'Gnome-calendar' state=floating
    bspc rule -a SPLASH state=floating 'desktop=^1'
    bspc rule -a Wpg state=floating
    bspc rule -a jupyter-qtconsole 'monitor=^1'
    bspc rule -a Gcolor3 state=floating
    bspc config external_rules_command "$HOME/.config/bspwm/vlc_fix"

    set -x SXHKD_SHELL /usr/bin/bash
    set -x _JAVA_AWT_WM_NONREPARENTING 1
    mkdir /tmp/kitty
    wmname LG3D

    runner &

    xsetroot -cursor_name left_ptr
    numlockx on
    sxhkd &
    xcape &
    picom &
    clipcatd &

    $HOME/.config/bspwm/receptacle_jump &
    $HOME/.config/bspwm/border_highlight &
    $HOME/.config/bspwm/delete_empty_desktops &

    ~/.fehbg
    env TRAY=none polybar -r main &
    env MONITOR=HDMI1 polybar -r main &

    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
    cmst -m -w 5 -i Snowy &
    ckb-next -b &
    redshiftx &
    notify-volume &
    notify-brightness &
    notify-brightness hdmi &
end
